{{- if .Values.enabled }}
{{- range $_, $clf_config := .Values.clfs }}
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: {{ $clf_config.name }}
  namespace: {{ $clf_config.namespace }}
  labels:
    app: {{ template "logginghelm.name" $ }}
    chart: {{ template "logginghelm.chart" $ }}
    release: {{ $.Release.Name }}
spec:
{{- fromJson $clf_config.spec | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}