{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-auth
  namespace: open-cluster-management
  labels:
    mcoa.openshift.io/signal: tracing
data:
  nothing: mTLS
{{- end }}