{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-auth
  namespace: open-cluster-management
  labels:
    mcoa.openshift.io/signal: logging
data:
{{- range $_, $dic := $.Values.outputs }}
{{- if eq $dic.type "cloudwatch" }}
  {{ $dic.name }}: StaticAuthentication
{{- else if eq $dic.type "loki" }}
  {{ $dic.name }}: mTLS
{{- end }}
{{- end }}
---
{{- end }}