apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-hub-cert-manager
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: redhat-openshift-cert-manager
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cert-manager-operator        
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              annotations:
                olm.providedAPIs: CertManager.v1alpha1.operator.openshift.io,Certificate.v1.cert-manager.io,CertificateRequest.v1.cert-manager.io,Challenge.v1.acme.cert-manager.io,ClusterIssuer.v1.cert-manager.io,Issuer.v1.cert-manager.io,Order.v1.acme.cert-manager.io
              name: cert-manager-operator
              namespace: cert-manager-operator
            spec:
              targetNamespaces:
              - cert-manager-operator
              upgradeStrategy: Default
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/openshift-cert-manager-operator.cert-manager-operator: ""
              name: openshift-cert-manager-operator
              namespace: cert-manager-operator
            spec:
              channel: stable-v1
              installPlanApproval: Automatic
              name: openshift-cert-manager-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
  - extraDependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: ConfigurationPolicy
      name: redhat-openshift-cert-manager
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-hub-root-certs
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: cert-manager.io/v1
              kind: Issuer
              metadata:
                name: selfsigned-issuer
                namespace: cert-manager
              spec:
                selfSigned: {}
          - complianceType: musthave
            objectDefinition:
              apiVersion: cert-manager.io/v1
              kind: Certificate
              metadata:
                name: mcoa-demo-ca
                namespace: cert-manager
              spec:
                isCA: true
                commonName: mcoa-demo-ca
                secretName: mcoa-demo-ca-secret
                privateKey:
                  algorithm: RSA
                  size: 4096
                  encoding: PKCS8
                issuerRef:
                  name: selfsigned-issuer
                  kind: Issuer
                  group: cert-manager.io
          - complianceType: musthave
            objectDefinition:
              apiVersion: cert-manager.io/v1
              kind: ClusterIssuer
              metadata:
                name: mcoa-demo-ca-issuer
                namespace: observability
              spec:
                ca:
                  secretName: mcoa-demo-ca-secret