{{- if and .Values.metrics.enabled }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-hub-metrics
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: minio-deployment
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: open-cluster-management-observability
        - complianceType: musthave
          objectDefinition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: minio
              namespace: open-cluster-management-observability
            spec:
              selector:
                matchLabels:
                  app.kubernetes.io/name: minio
              strategy:
                type: Recreate
              template:
                metadata:
                  labels:
                    app.kubernetes.io/name: minio
                spec:
                  containers:
                    - command:
                        - /bin/sh
                        - -c
                        - |
                          mkdir -p /storage/thanos && \
                          /usr/bin/docker-entrypoint.sh minio server /storage
                      env:
                        - name: MINIO_ROOT_USER
                          value: minio
                        - name: MINIO_ROOT_PASSWORD
                          value: minio123
                      image: minio/minio:RELEASE.2023-05-27T05-56-19Z
                      imagePullPolicy: IfNotPresent
                      name: minio
                      ports:
                        - containerPort: 9000
                      volumeMounts:
                        - mountPath: /storage
                          name: storage
                  volumes:
                    - name: storage
                      persistentVolumeClaim:
                        claimName: minio
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              labels:
                app.kubernetes.io/name: minio
              name: minio
              namespace: open-cluster-management-observability
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: thanos-object-storage
              namespace: open-cluster-management-observability
            stringData:
              thanos.yaml: |
                type: s3
                config:
                  bucket: thanos
                  endpoint: minio.open-cluster-management-observability.svc.cluster.local:9000
                  insecure: true
                  access_key: minio
                  secret_key: minio123
            type: Opaque
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Service
            metadata:
              name: minio
              namespace: open-cluster-management-observability
            spec:
              ports:
                - port: 9000
                  protocol: TCP
                  targetPort: 9000
              selector:
                app.kubernetes.io/name: minio
              type: ClusterIP
  - extraDependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: ConfigurationPolicy
      name: minio-deployment
    objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mco-config
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteAll
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: observability.open-cluster-management.io/v1beta2
              kind: MultiClusterObservability
              metadata:
                name: observability
                namespace: open-cluster-management-observability
              spec:
                observabilityAddonSpec: {}
                storageConfig:
                  metricObjectStorage:
                    name: thanos-object-storage
                    key: thanos.yaml
{{- end }}