apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcoa-demo-workload
  namespace: openshift-mcoa-demo-workload

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcoa-demo-workload-role
  namespace: openshift-mcoa-demo-workload
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcoa-demo-workload-role-binding
  namespace: openshift-mcoa-demo-workload
subjects:
- kind: ServiceAccount
  name: mcoa-demo-workload
  namespace: openshift-mcoa-demo-workload
roleRef:
  kind: Role
  name: mcoa-demo-workload-role
  apiGroup: rbac.authorization.k8s.io

---