apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python
spec:
  selector:
    matchLabels:
      app: my-python
  replicas: 1
  template:
    metadata:
      labels:
        app: my-python
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: myapp
        image: ghcr.io/open-telemetry/opentelemetry-operator/e2e-test-app-python:main
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          privileged: false
          runAsNonRoot: true
