{{- if .Values.tracing.enabled }}
{{- range $_, $cluster_name := .Values.spokeClusters }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-{{ $cluster_name }}-otlp
  namespace: {{ $cluster_name }}
  labels:
    mcoa.openshift.io/signal: tracing
  annotations:
    tracing.mcoa.openshift.io/target-output-name: otlp
data:
  endpoint: test-collector-observability.apps.{{ $.Values.hubClusterName }}:80
{{- end }}
{{- end }}