{{- if .Values.enabled }}
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
  labels:
    app: {{ template "netflowhelm.name" . }}
    chart: {{ template "netflowhelm.chart" . }}
    release: {{ .Release.Name }}
spec:
{{- fromJson .Values.flowCollectorSpec | toYaml | nindent 2 }}
{{- end }}
