apiVersion: v1
description: A Helm chart to help configure each signal deployed by mcoa
name: addon-config
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: logging
  repository: 'file://./charts/logging'
  condition: logging.enabled
- name: tracing
  repository: 'file://./charts/tracing'
  condition: tracing.enabled