apiVersion: v1
kind: Secret
metadata:
  name: tracing-otlp-auth
  namespace: {{ .Values.spokeClusterName }}
type: Opaque
data:
  "tls.key": {{ .Values.otelCollectorSecret.tlsKey | b64enc }}
  "tls.crt": {{ .Values.otelCollectorSecret.tlsCrt | b64enc }}
  "ca-bundle.crt": {{ .Values.otelCollectorSecret.caCrt | b64enc }}
